services:
  - type: web
    name: greenloop-yolo-api
    runtime: python
    rootDir: backend/yolon8
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
